### ISSUE TITLE
Hospedagem domínio - pesquisar

### ISSUE THREAD

**Issue by ReginaldoMalaquias** [ReginaldoMalaquias/ppeletronico#1]
> > * [x]   - 30 dias Hosgator
> > * [x]   - 365 dias Hosgator
> > * [x]   - 6 meses Hosgator
> > * [x]    - Escolher hospedagem com plano
> > * [x]    - Configuar dns
> > * [ ]    - Configuar correio na loja virtual
> > * [ ]    - Configuar pagamento no cartão
> > * [ ]    - Ativar página inicial do site

**Comment by PPAULLA22** [comment]
> * [x]  - 30 dias Hosgator
> * [x]  -  365 dias Hosgator
> * [x]  -  6 meses Hosgator
> * [x]   - Escolher hospedagem com plano
> * [ ]   - Configuar dns
> * [ ]   - Configuar correio na loja virtual

**Comment by ReginaldoMalaquias** [comment]
> > * [x]   - 30 dias Hosgator
> > * [x]   - 365 dias Hosgator
> > * [x]   - 6 meses Hosgator
> > * [x]    - Escolher hospedagem com plano
> > * [x]    - Configuar dns
> > * [ ?]    - Configuar correio na loja virtual
> > * [ ]    - Configuar pagamento no cartão

**Comment by PPAULLA22** [comment]
> * [x]  - 30 dias Hosgator
> * [x]  -  365 dias Hosgator
> * [x]  -  6 meses Hosgator
> * [x]   - Escolher hospedagem com plano
> * [ ]   - Configuar dns



> * Configuar correio na loja virtual
> * Configuar correio na loja virtual 2
